### ISSUE TITLE
Profile and optimize /cartelera

### ISSUE THREAD

**Issue by ronyb29** [kengru/Giru#16]

**Comment by ronyb29** [comment]
Most of the time is being spent opening and closing ssl connections.

There is no easy way to optimize since the IMDB client uses urllib and would have to be modified to support keep alive (requests, urllib3)

An option would be to make do the requests and parse the response himself. 

![image](https://user-images.githubusercontent.com/1606872/41751616-3b10e336-7590-11e8-8507-b37cfa132740.png)

[Giru16.pstat.zip](https://github.com/kengru/Giru/files/2125739/Giru16.pstat.zip)

**Comment by ronyb29** [comment]
Writing a custom request parser improved a bit, but not enough. forgot to take the screenshot of stats before scraping the idea.

**Comment by ronyb29** [comment]
Gonna try with api.cine.com.do now

**Comment by ronyb29** [comment]
only sure-fire way to improve speed and avoid caching is to change to omdb. the OMDB api includes ratings from metacritic, rotten tomatoes and IMDB. But for some tease some blockbusters won't have their IMDB score shown, thyre listed as 'N/A'

**Comment by kengru** [comment]
Fixed with PR #26
