### ISSUE TITLE
Giru anuncia su muerte / resurrección 

### ISSUE THREAD

**Issue by stevencatalino** [kengru/Giru#19]
Como Jesús

**Comment by ronyb29** [comment]
se muere porque se va a beber el fin de semana? 😂😂

**Comment by kengru** [comment]
@ronyb29 esto es para que cuando se vaya a apagar Giru, de un mensaje de que se va a apagar, igual cuando se vaya a prender.

**Comment by ronyb29** [comment]
En teoria ya nunca se va a bajar, no?

**Comment by kengru** [comment]
""

**Comment by ronyb29** [comment]
Quiero decir, con el CI siempre va a estar arriba,no?

**Comment by kengru** [comment]
Sí, we can close this.
