### ISSUE TITLE
Comando para buscar pelicula

### ISSUE THREAD

**Issue by arsenio14** [kengru/Giru#25]
Que cuando se le de el comando el busque el link en imdb o alguna otra pagina la pelicula que se le pidio

**Comment by arsenio14** [comment]
Si

**Comment by ronyb29** [comment]
Se puede hacer que cuando le das al score te lleve a esa pagina, ie. si le das a la palomita te lleva a imdv, si le das al tomate, te lleva a rottentomatoes.

**Comment by arsenio14** [comment]
Cool, pero yo queria era que cuando se hablara de peliculas en general,
para recomendar una el lo busque de una vez, que no tenga que ser solo la
de las cartelera, pero si no se puede no importa

**Comment by ronyb29** [comment]
Se puede manín, confía.

**Comment by ronyb29** [comment]
Se puede usar @imdb y ya.
