### ISSUE TITLE
implementar CI cada vez que se hace un PR (o commit) a master

### ISSUE THREAD

**Issue by ronyb29** [kengru/Giru#28]

**Comment by ronyb29** [comment]
wip branch: internal/CI

**Comment by ronyb29** [comment]
Hasta ahora se cargan las configuraciones de un .env (ya que Digital ocean no de teja configurarlas por servidor) y se inicia solo Giru cada vez que el droplet sube (rc.local)

**Comment by kengru** [comment]
Pregunta, internal/CI es donde hacia donde se harán los pull requests para que luego manualmente se haga el merge a master pal CI, o es de donde Giru sacará el source code?

**Comment by ronyb29** [comment]
Es adónde se harán los commit para este pr solamente. El CI correrá sobre
Master.
