### ISSUE TITLE
Change the /padondehoy to be random while still being a message by day.

### ISSUE THREAD

**Issue by kengru** [kengru/Giru#3]

**Comment by ronyb29** [comment]
RFC: 

Giru debería elegir la respuesta de un catalogo del día, es decir, debería haber un catalogo de actividades para el lunes, para el martes, para el miércoles, etc.

Ademas, debería dar la misma respuesta si se le pregunta de nuevo el mismo día, por ejemplo el jueves 15 le preguntan /padondehoy y decide que es dia de 2x1 en shots (lol), si le vuelven a preguntar en ese grupo durante el mismo día 15, debería dar la misma respuesta en vez de elegirla al azar.

**Comment by kengru** [comment]
Solo hay que diseñar la forma de traquear las cosas de los chats. Y agregarlo a la nube, donde sea que @francisbrito va a guardar los saved messages en #1 .

**Comment by ronyb29** [comment]
Pudiéramos dejar esas repuestas en un cache en memoria?
Pudieran cambiar si se re-inicia ese día, pero no veo prob con eso.

**Comment by ronyb29** [comment]
Sigamos la conversación en #6

**Comment by ronyb29** [comment]
PR #6 implementa este feature y se mergeo.
