### ISSUE TITLE
Mantener los scores limitados a cada grupo

### ISSUE THREAD

**Issue by Alghieri** [kengru/Giru#36]
Que los scores difieran entre grupos, limitando las puntuaciones a cada grupo sin que los +1 o -1 de un chat cuenten en otro. También que los que no tienen puntos aparezcan con cero en vez de no aparecer.

**Comment by ronyb29** [comment]
Y los mensajes guardados

**Comment by ronyb29** [comment]
@kengru que crees de que los scores y los "saved" Sean por grupo?

**Comment by kengru** [comment]
@ronyb29 
Eso e lo que #13 quiere decir, por lo menos los de saved, no existia score by that time asi que sure, claro.

Puedo hacer ambas cosas pero by the weekend, this week im busy af.

**Comment by kengru** [comment]
Fixed by @ronyb29 on https://github.com/kengru/Giru/pull/72
