### ISSUE TITLE
Mensaje particular cuando digan mucho su nombre

### ISSUE THREAD

**Issue by stevencatalino** [kengru/Giru#5]
Si se menciona mucho "giru" en un short timespan o muchas veces continuas sin ningun otro comando, que responda otro mensaje particular y deje de decir "Dimelo." por un rato. A ve si se evita que se spammee el "Dimelo." 

Alternativamente, que diga vainas aparte de "Dimelo."  cuando lea "giru".

**Comment by francisbrito** [comment]
Creo que una solución viable para esto es hacer que el solo responda cuando se le haga mention.

**Comment by stevencatalino** [comment]
Okay, yo no soy programador pero chequea esta idea. 
Ponerle un contador de cada vez que lea "giru". Usualmente el no va a decir na, pero si el numero es divisible entre 7 el te devuelve un "dimelo", y si es divisible entre 10 el te devuelve un "mmg que ute quiere". Brega con lo numeros pa' controlar la frecuencia. Cuidado cuando el numero es divisible entre 7 y 10, que evalue uno y despues el otro. No importa si el contador se resetea cada vez que el se vaya offline, lo importante es que su respuesta sea menos predecible. Uno no va a estar contando.

**Comment by kengru** [comment]
@francisbrito Sí, debemos de ver.

**Comment by ronyb29** [comment]
this happened, didn't it?
