### ISSUE TITLE
Aiuda no aiuda

### ISSUE THREAD

**Issue by ronyb29** [kengru/Giru#57]
La ayuda debería cargar los comandos y sus descripciones de algún modelo en el código para que siempre este actualizada. Por ejemplo -recon no está

**Comment by kengru** [comment]
Pero duro el niño, also, la ayuda debería de mandartela privada.

**Comment by kengru** [comment]
Fixing the sending to a private chat on #60.

**Comment by kengru** [comment]
Fixed, still missing el modelo en el codigo.

**Comment by ronyb29** [comment]
Hay una lista de comando que se cargan en __main__ esta noche reviso a ver si lo implemento

**Comment by ronyb29** [comment]
resolved on #65
